### ISSUE TITLE
Add a inlay hint when hovering over the Itemstack variable

### ISSUE THREAD

**Issue by TheTzdDark** [raylras/zenscript-intelli-sense#117]
With the introduction of inlay hints about the name of Itemstack, I think it should also be added to the window that appears when you hover with ctrl over the variable containing itemstack.

![image](https://github.com/raylras/zenscript-intelli-sense/assets/79448439/50fd7b94-6545-4a80-b603-bc78e9c52246)

**Comment by raylras** [comment]
Actually, this is the 'Go to Definition' feature. VSCode will display the code at the definition as it is, and it cannot be customized to display anything else.

**Comment by TheTzdDark** [comment]
Understood, thanks
