### ISSUE TITLE
Syntax Highlighting problem: `%` symbol escaping strings

### ISSUE THREAD

**Issue by Krutoy242** [raylras/zenscript-intelli-sense#97]
When string ends with `%'` it cant capture end of string
  > 
  > ![image](https://github.com/raylras/zenscript-intelli-sense/assets/936618/ddca9e8c-5abb-4afc-a4d6-13caaa32f36e)
  > 
  > ![image](https://github.com/raylras/zenscript-intelli-sense/assets/936618/7aeed272-a0f7-4b41-a10a-ee4f9b999f80)

**Comment by raylras** [comment]
This issue reproduced successfully on v0.15.1, but not on v0.16.0. It should have been fixed in f84a569b2b51968b0a4d5b12a926572c15249ab2. Consider using v0.16.0

**Comment by Krutoy242** [comment]
Im already using `v0.16.0`
![image](https://github.com/raylras/zenscript-intelli-sense/assets/936618/51f40182-684a-4258-807f-17f5d1c91971)

**Comment by raylras** [comment]
I didn't realize I got GitHub to close this issue. Anyway, please try v0.16.1
